#let text-fonts = ("Times New Roman", "SimSun")
#let bold-fonts = ("Times New Roman", "SimHei")
#let emph-fonts = ("Times New Roman", "KaiTi")
#let code-fonts = ("JetBrains Mono", "Consolas", "FangSong")
#let title-fonts = ("Times New Roman", "STZhongsong")
#let heading-fonts = ("Times New Roman", "STHeiti")
#let remark-fonts = ("Times New Roman", "FangSong")
#let heading-num-fonts = ("Cambria")